-- Run: psql "$DATABASE_URL" -f backend/db/migrations/001_init.sql
CREATE TABLE IF NOT EXISTS urls (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url"         text NOT NULL,
  "shortCode"   varchar(10) NOT NULL UNIQUE,
  "accessCount" integer NOT NULL DEFAULT 0,
  "createdAt"   timestamptz NOT NULL DEFAULT now(),
  "updatedAt"   timestamptz NOT NULL DEFAULT now()
);
